#ifndef MANAGED_OBJECT_BITS_H
#define MANAGED_OBJECT_BITS_H

#define MANAGED_OBJECT_BITS_BIT_NONE 0b00000000
#define MANAGED_OBJECT_BITS_BIT_1    0b00000001
#define MANAGED_OBJECT_BITS_BIT_2    0b00000010
#define MANAGED_OBJECT_BITS_BIT_3    0b00000100
#define MANAGED_OBJECT_BITS_BIT_4    0b00001000
#define MANAGED_OBJECT_BITS_BIT_5    0b00010000
#define MANAGED_OBJECT_BITS_BIT_6    0b00100000
#define MANAGED_OBJECT_BITS_BIT_7    0b01000000
#define MANAGED_OBJECT_BITS_BIT_8    0b10000000
#define MANAGED_OBJECT_BITS_BIT_ALL  0b11111111

#define MANAGED_OBJECT_BITS_WITH_BIT(bits, bit)     ((bits) | (bit))
#define MANAGED_OBJECT_BITS_WITHOUT_BIT(bits, bit)  ((bits) & ~(bit))
#define MANAGED_OBJECT_BITS_SET_BIT(bits, bit)      ((bits) = MANAGED_OBJECT_BITS_WITH_BIT((bits), (bit)))
#define MANAGED_OBJECT_BITS_CLEAR_BIT(bits, bit)    ((bits) = MANAGED_OBJECT_BITS_WITHOUT_BIT((bits), (bit)))
#define MANAGED_OBJECT_BITS_HAS_BIT(bits, bit)      (((bits) & (bit)) == (bit))

#endif
